name: tagpr
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    outputs:
      tagpr-tag: ${{ steps.tagpr.outputs.tag }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: tagpr
        name: Run tagpr
        uses: Songmu/tagpr@84850af451fc53753c6685a3a6a2af7beef23607 # v1.18.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger release Workflow
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        continue-on-error: true
        if: steps.tagpr.outputs.tag != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let refs = '${{ fromJson(steps.tagpr.outputs.pull_request).head.ref }}'

            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: refs,
              inputs: {
                tag: '${{ steps.tagpr.outputs.tag }}'
              },
            })
