name: Test build
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-job:
    name: Test job.
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@689c87690ef3b954b5039bcb15589863c9e021a1 # v3.11.1
        with:
          reporter: github-pr-review
          level: warning
          textlint_flags: "slides.md"
          filter_mode: "diff_context"
      - run: make build
